### PR TITLE
Aarch64 Tweaks

### PR DESCRIPTION
**Pull request by wezm**
- Use `std::os::raw::c_char`
- Enable CI on ARM

### CODE REVIEW

**Comment by brendanzab** [comment]
Is it possible to remove the need for `libc` in `fontconfig-sys` as well?

**Comment by brendanzab** [comment]
It's not a big deal though - just curious. Otherwise looks good!

**Review by brendanzab — APPROVED** [review]

**Comment by wezm** [comment]
> Is it possible to remove the need for `libc` in `fontconfig-sys` as well?

It is! Good idea.

**Comment by brendanzab** [comment]
Yeah, I think that was part of my reasoning for accepting the addition of `libc` in the original PR, so it was on my mind!

**Review by adrianwong — APPROVED** [review]
Nice work!

**Pull request merged**
