### PR TITLE
New safe bindings.

### PR DESCRIPTION
**Pull request by songww**

### CODE REVIEW

**Comment by songww** [comment]
Hi, @wezm 

 How about this one? If it is not able to be merged, I will publish a branch version on crates.io .

I will add more tests.

**Comment by wezm** [comment]
Thanks for the heads up. I'll probably get time to review on Tuesday (UTC+10).

**Comment by songww** [comment]
> 

Ok, thanks for your time.

**Comment by wezm** [comment]
Hi @songww 

I've had a look over the changes. They look good overall and I understand that you've probably put a lot of time into this but it's almost a complete rewrite of the higher-level crate. I think it is probably best that you publish it as a separate crate.

It might be nice to avoid having another `fontconfig-sys` crate on crates.io so I would be happy to pull in your changes to that part of the repo and publish a new version.

If you do decide to publish your work as a new crate may I please ask that you ensure all metadata in the `Cargo.toml` `README` (including badges, Other Fontconfig Crates, and Credits section) are updated to point at your repository, docs, CI, etc. to avoid any confusion.

**Comment by songww** [comment]
Ok, thanks

**Pull request closed without merging**
